title: "Paulo Arruda's Blog"
email: parrudaj@gmail.com
description: >-
  Thoughts on software engineering, AI, and more.
baseurl: "" # Leave blank if deploying to root
url: "https://parruda.net" # Your custom domain

twitter_username: parrudanet
github_username: parruda

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Halifax # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Paulo Arruda"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Software engineer, AI enthusiast, and more."
  links:
    - label: "x.com"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://x.com/parrudanet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parruda"

footer:
  links:
    - label: "x.com"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://x.com/parrudanet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parruda"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/